osx_image: xcode9
language: objective-c
cache:
- bundler
- cocoapods

before_install:
  - pod repo update

script:
  - xcodebuild clean test -quiet -workspace Konkani\ Recipes.xcworkspace -scheme Konkani\ Recipes -destination 'platform=iOS Simulator,name=iPhone 5s'
  - bundle exec danger

after_success:
  - bash <(curl -s https://codecov.io/bash)
