osx_image: xcode9
language: objective-c
cache:
- bundler
- cocoapods

script:
  - xcodebuild clean test -quiet -workspace Konkani\ Recipes.xcworkspace -list
  - xcodebuild clean test -quiet -workspace Konkani\ Recipes.xcworkspace -scheme Konkani\ Recipes -destination 'platform=iOS Simulator,name=iPhone 5s'

after_success:
  - bash <(curl -s https://codecov.io/bash)
